name: hist-obs
channels:
  - defaults
  - conda-forge
dependencies:
  - aioboto3==10.1.0
  - aiobotocore==2.4.0
  - aiohttp==3.8.4  
  - beautifulsoup4==4.11.1
  - blas==1.0
  - blosc==1.21.3
  - boto3==1.24.59
  - botocore==1.27.59
  - cfitsio==3.470
  - cftime==1.6.3
  - cfgrib==0.9.12.0
  - curl==8.1.1
  - cython==3.0.10
  - datetime==4.4
  - dask==2022.8.1
  - dask-core==2023.6.0
  - dask-labextension==7.0.0
  - descartes==1.1.0
  - fiona==1.9.4.post1
  - geographiclib==2.0
  - geopandas==0.11.1
  - geopy==2.3.0
  - hdf4==4.2.13
  - hdf5==1.10.6
  - h5netcdf==1.0.2
  - h5py==3.9.0
  - h5pyd==0.18.0
  - intel-openmp==2023.1.0
  - matplotlib==3.7.2
  - matplotlib-inline==0.1.6
  - mpi4py==3.1.6
  - nbconvert==7.16.4
  - netcdf4==1.6.4
  - numpy==1.25.0
  - openpyxl==3.0.10
  - pandas==1.5.0
  - pip==24.0
  - pygeos==0.14
  - pywavelets==1.4.1
  - rasterio==1.3.8
  - s3fs==2022.11.0
  - s3transfer==0.6.1
  - scikit-image==0.20.0
  - scikit-learn==1.2.2
  - scipy==1.11.1
  - setuptools==67.8.0
  - shapely==1.8.1.post1
  - sqlite==3.41.2
  - tk==8.6.12
  - urllib3==1.26.16
  - xarray==2024.5.0
  - xclim==0.49.0
  - xesmf==0.8.5
  - xlswriter==3.1.9
  - pip:
      - fastkde==2.0.1
      - ipykernel==6.29.3
      - ipython==8.18.1
      - jupyterlab==4.2.2
      - notebook==7.2.1
      - simplempi==0.1.4
