channels:
  - conda-forge
dependencies:
  - python=3.10
  - black=24.8.0
  - boto3=1.24.59
  - dask=2024.2.1
  - geopandas=0.11.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jupyterlab==4.2.2
  - matplotlib=3.5.3
  - netcdf4=1.6.0
  - numpy=1.26.4
  - pandas=1.5.0
  - requests=2.32.3
  - s3fs=2022.11.0
  - s3transfer=0.6.0
  - scipy=1.13.1
  - setuptools=75.1.0
  - smart_open=6.3.0
  - statsmodels=0.14.2
  - tqdm=4.66.4
  - xarray=2022.3.0